Listen 443
<VirtualHost *:443>
    DocumentRoot "/var/www/html/nextcloud/"
    ServerName docs.anyit.net

    SSLEngine on
    SSLCertificateFile /etc/httpd/ssl/nextcloud.crt
    SSLCertificateKeyFile /etc/httpd/ssl/nextcloud.key

    <Directory "/var/www/html/nextcloud/">
        Options +FollowSymLinks +MultiViews
        AllowOverride All
        Require all granted
        DirectoryIndex index.php
    </Directory>

    # Proxy Collabora Online
    AllowEncodedSlashes NoDecode
    ProxyPreserveHost On

    # static file serve
    ProxyPass           /browser/ http://127.0.0.1:9980/browser/ retry=0
    ProxyPassReverse    /browser/ http://127.0.0.1:9980/browser/

    # WOPI discovery URL
    ProxyPass           /hosting/discovery http://127.0.0.1:9980/hosting/discovery retry=0
    ProxyPassReverse    /hosting/discovery http://127.0.0.1:9980/hosting/discovery

    # Capabilities
    ProxyPass           /hosting/capabilities http://127.0.0.1:9980/hosting/capabilities retry=0
    ProxyPassReverse    /hosting/capabilities http://127.0.0.1:9980/hosting/capabilities

    # Main websocket
    ProxyPassMatch      "/cool/(.*)/ws$"      ws://127.0.0.1:9980/cool/$1/ws nocanon

    # Admin console websocket
    ProxyPass           /cool/adminws ws://127.0.0.1:9980/cool/adminws

    # Download as, Fullscreen presentation and Image upload operations
    ProxyPass           /cool http://127.0.0.1:9980/cool
    ProxyPassReverse    /cool http://127.0.0.1:9980/cool

    # PHP 파일 처리 강제 지정 (PHP-FPM 연결)
    <FilesMatch \.php$>
        SetHandler "proxy:unix:/run/php-fpm/www.sock|fcgi://localhost"
    </FilesMatch>
</VirtualHost>
